
[general]
server_check_url=http://www.gstatic.com/generate_204
server_check_timeout=2000
resource_parser_url=https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/IP_API.js

[dns]
no-system
no-ipv6
server=223.5.5.5
server=119.29.29.29

[policy]
static=代理, proxy, direct
static=电报, proxy, direct
static=苹果服务, proxy, direct
static=Final, proxy, direct

[server_remote]
# 机场订阅

[filter_remote]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list, tag=苹果, force-policy=苹果服务, update-interval=-1, opt-parser=false, inserted-resource=true, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Telegram/Telegram.list, tag=TG, force-policy=电报, update-interval=-1, opt-parser=false, inserted-resource=true, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list, tag=国外流媒体, force-policy=代理, update-interval=-1, opt-parser=false, inserted-resource=true, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Global/Global.list, tag=国外网站, force-policy=代理, update-interval=-1, opt-parser=false, inserted-resource=true, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/China/China.list, tag=国内网站, force-policy=direct, update-interval=-1, opt-parser=false, inserted-resource=true, enabled=true

[rewrite_remote]


[server_local]
# 本地节点vless=

[filter_local]
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
ip-cidr, 224.0.0.0/24, direct
geoip, CN, direct
final, Final

[rewrite_local]


[mitm]
